CREATE TABLE user_planet_info (
    user_id NUMBER,
    CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES credenciales_usuario(user_id),
    planet_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    planet_name VARCHAR2(50),
    resource_metal_amount NUMBER,
    resource_dauterion_amount NUMBER,
    resource_defense NUMBER,
    resource_attack NUMBER,
    battle_counter NUMBER,
    missile_launcher_remaining number,
    ion_cannon_remaining NUMBER,
    plasma_cannon_remaining number,
    light_hunter_remainig NUMBER,
    heavy_hunter_remainig number,
    battleship_remainig NUMBER,
    armored_ship_remainig number
);

/*probamos a introducir datos para comprobar que este correcto*/



INSERT INTO user_planet_info (user_id, planet_name,
    resource_metal_amount, 
    resource_dauterion_amount,
    resource_defense ,
    resource_attack ,
    battle_counter ,
    missile_launcher_remaining,
    ion_cannon_remaining,
    plasma_cannon_remaining ,
    light_hunter_remainig,
    heavy_hunter_remainig ,
    battleship_remainig,
    armored_ship_remainig)
SELECT user_id, 'Espanya',1,2,3,4,5,6,7,8,9,10,11,12
FROM credenciales_usuario;