CREATE TABLE credenciales_usuario (
    user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_password VARCHAR2(15),
    user_name VARCHAR2(15) UNIQUE);

/* generamos un usuario d eprueba donde solo hace falta el pasword y el name, pero el username, tien eque ser unico, para que los agenos no entren a la sesión del usuario en especifico, luego de haber introducido las credenciales, creandolo, el user id se gener automaticmaente
*/

INSERT INTO credenciales_usuario (user_password, user_name)
VALUES ('pan de molde', 'manolo');
